import React from 'react';
import { motion } from 'framer-motion';
import WorkflowStep from './WorkflowStep.jsx';
import ProgressTracker from './ProgressTracker.jsx';
import SavingsPlanner from './SavingsPlanner.jsx';

/* STEP 5-6 — the generated workflow, then the same workflow tracked as tasks
   get completed. Before "Start Workflow" the actions are visible but locked. */
const WorkflowTimeline = ({ session, ...motionProps }) => {
  const {
    workflow,
    plan,
    analysis,
    intent,
    answers,
    updateAnswer,
    status,
    completedTaskIds,
    toggleTask,
    startWorkflow,
    progress,
    source,
    account,
  } = session;

  const steps = plan?.steps || [];
  const active = status !== 'draft';

  return (
    <motion.div className="wf-stage" {...motionProps}>
      <div className="wf-timeline-head">
        <p className="wf-eyebrow">Your workflow</p>
        <h2 className="wf-h2">{analysis?.intent || intent}</h2>
        <p className="wf-meta">
          {steps.length} phases · {progress.total} actions
          {source === 'ai' ? ' · generated with FlowState AI' : ' · generated by the FlowState engine'}
        </p>
      </div>

      {active && <ProgressTracker progress={progress} category={workflow.category} />}

      {workflow.planner === 'savings' && (
        <SavingsPlanner answers={answers} updateAnswer={updateAnswer} />
      )}

      <ol className="wf-steps">
        {steps.map((step, index) => (
          <WorkflowStep
            key={step.id}
            step={step}
            index={index}
            defaultOpen={index === 0}
            tasksEnabled={active}
            completedTaskIds={completedTaskIds}
            onToggleTask={toggleTask}
          />
        ))}
      </ol>

      {!active ? (
        <div className="wf-start-row">
          <p className="wf-meta wf-meta-quiet">
            Review the plan, expand anything you want detail on, then start when you are ready.
          </p>
          <button type="button" className="wf-btn wf-btn-primary" onClick={startWorkflow}>
            Start Workflow
            <span aria-hidden="true">→</span>
          </button>
        </div>
      ) : (
        <p className="wf-meta wf-meta-quiet wf-timeline-foot">
          Tick actions as you finish them. Progress is saved on this device
          {account?.email ? ' and to your FlowState account.' : ' — sign in to keep it across devices.'}
        </p>
      )}
    </motion.div>
  );
};

export default WorkflowTimeline;
